name: React CI

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build app
        working-directory: frontend
        run: npm run build

      - name: Run tests (optional)
        working-directory: frontend
        run: npm test || echo "No tests"
